site_name: eGeoffrey user documentation
nav:
  - 'Welcome': 'index.md'
  - 'Say hi to him': 'say-hi-to-him/getting-started-guide.md'
  - 'What is it made of?':
    - 'Sensors and services': 'what-is-it-made-of/sensors-and-services.md'
  - 'Understand it':
    - 'To be done': 'understand-it/to-be-done.md'
  - 'Use it':
    - 'To be done': 'use-it/to-be-done.md'
theme: 
  name: material
extra_css:
- css/custom.css
