site_name: eGeoffrey User Documentation
site_url: https://www.egeoffrey.com
repo_url: https://www.egeoffrey.com/#resources
repo_name: egeoffrey.com
nav:
  - 'Welcome': 'index.md'
  - 'Installation':
    - 'Where to Install': 'installation/where.md'
    - 'Installation process': 'installation/install.md'
    - 'Troubleshooting': 'installation/troubleshooting.md'
  - 'Initial Setup': 
    - 'First Access': 'setup/gui.md'
    - 'House Setup': 'setup/house.md'
  - 'Configure eGeoffrey':
    - 'Typical Workflow': 'configure/workflow.md'
    - 'Install a Package': 'configure/packages.md'
    - 'Configure a Module': 'configure/modules.md'
    - 'Add a Sensor': 'configure/sensors.md'
    - 'Visualize your data': 'configure/pages.md'
    - 'Configure Rules': 'configure/rules.md'
    - 'Manage your Users': 'configure/users.md'
    - 'Upgrades': 'configure/upgrade.md'
    - 'Remote Access': 'configure/remote.md'
    - 'Multi House Support': 'configure/multi-house.md'
    - 'Troubleshooting': 'configure/troubleshooting.md'
  - 'HOW TOs': 'howto.md'
  - 'Need Help?': 'help.md'
theme: 
  name: material
google_analytics: ['UA-1633536-8', 'docs.egeoffrey.com']
extra_css:
- css/custom.css
